source :rubygems
gem "sinatra"
gem "slim"
gem "sass"
gem "dm-core"
gem "dm-migrations"
gem "thin"
gem "pg", :group => :production
gem "dm-postgres-adapter", :group => :production
gem "sqlite3", :group => :development
gem "dm-sqlite-adapter", :group => :development